#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=3

app=$YNH_APP_INSTANCE_NAME

install_type=$(ynh_app_setting_get --app=$app --key=install_type)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)
auto_detect_failure=$(ynh_app_setting_get --app=$app --key=auto_detect_failure)

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Backing up the main app directory..."

ynh_backup --src_path="$final_path"

#=================================================
# SPECIFIC BACKUP
#=================================================

if [ "$install_type" == "main" ]
then

	#=================================================
	# BACKUP LOGROTATE
	#=================================================
	ynh_script_progression --message="Backing up logrotate configuration..."

	ynh_backup --src_path="/etc/logrotate.d/$app"

	#=================================================
	# BACKUP THE CRON FILE
	#=================================================
	ynh_script_progression --message="Backing up cron file..."

	ynh_backup --src_path="/etc/cron.d/$app"
else
	#=================================================
	# BACKUP USER DIRECTORIES
	#=================================================
	ynh_script_progression --message="Backing up user directories..."

	ynh_backup --src_path="/home/$app/bin"
	ynh_backup --src_path="/home/$app/lib"
	ynh_backup --src_path="/home/$app/lib64"
	ynh_backup --src_path="/home/$app/.ssh"

	#=================================================
	# BACKUP THE CRON FILE
	#=================================================

	if [ $auto_detect_failure -eq 1 ]
	then
		ynh_script_progression --message="Backing up cron file..."
		ynh_backup --src_path="/etc/cron.d/auto_deploy_fallback"
	fi
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)." --last
