#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Load settings" --weight=3

app=$YNH_APP_INSTANCE_NAME

install_type=$(ynh_app_setting_get $app install_type)
final_path=$(ynh_app_setting_get $app final_path)
auto_detect_failure=$(ynh_app_setting_get $app auto_detect_failure)

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Backup the app main dir"

ynh_backup "$final_path"

#=================================================
# SPECIFIC BACKUP
#=================================================

if [ "$install_type" == "main" ]
then

	#=================================================
	# BACKUP LOGROTATE
	#=================================================
	ynh_script_progression --message="Backup logrotate configuration"

	ynh_backup "/etc/logrotate.d/$app"

	#=================================================
	# BACKUP THE CRON FILE
	#=================================================
	ynh_script_progression --message="Backup cron file"

	ynh_backup "/etc/cron.d/$app"
else
	#=================================================
	# BACKUP USER DIRECTORIES
	#=================================================
	ynh_script_progression --message="Backup user directories"

	ynh_backup "/home/$app/bin"
	ynh_backup "/home/$app/lib"
	ynh_backup "/home/$app/lib64"
	ynh_backup "/home/$app/.ssh"

	#=================================================
	# BACKUP THE CRON FILE
	#=================================================

	if [ $auto_detect_failure -eq 1 ]
	then
		ynh_script_progression --message="Backup cron file"
		ynh_backup "/etc/cron.d/auto_deploy_fallback"
	fi
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Backup completed" --last
