#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=2

app=$YNH_APP_INSTANCE_NAME

install_type=$(ynh_app_setting_get --app=$app --key=install_type)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)
ssh_host=$(ynh_app_setting_get --app=$app --key=ssh_host)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Removing dependencies..." --weight=7

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_script_progression --message="Removing app main directory..."

# Remove the app directory securely
ynh_secure_remove --file="$final_path"

if [ "$install_type" == "main" ]
then
	#=================================================
	# REMOVE LOGROTATE CONFIGURATION
	#=================================================
	ynh_script_progression --message="Removing logrotate configuration..."

	# Remove the app-specific logrotate config
	ynh_remove_logrotate
	ynh_secure_remove --file="/var/log/$app"
fi

#=================================================
# SPECIFIC REMOVE
#=================================================

if [ "$install_type" == "main" ]
then
	#=================================================
	# REMOVE THE CRON FILE
	#=================================================

	ynh_secure_remove --file="/etc/cron.d/$app"

	#=================================================
	# REMOVE THE HOST FROM THE KNOWN HOST LIST
	#=================================================

	sed -i "/$ssh_host/d" /root/.ssh/known_hosts

	#=================================================
	# REMOVE DEDICATED USER
	#=================================================
	ynh_script_progression --message="Removing the dedicated system user..."

	ynh_system_user_delete --username=$app
	ynh_secure_remove --file="/home/$app"

	#=================================================
	# REMOVE THE CHROOT FROM THE SSH CONFIG
	#=================================================
	ynh_script_progression --message="Removing the chroot from the ssh config..."

	sed -i "/# Automatically added by $app/d" /etc/ssh/sshd_config

	# Reload ssh service
	ynh_systemd_action --action=reload --service_name=ssh
else
	#=================================================
	# REMOVE THE CRON FILE
	#=================================================

	ynh_secure_remove --file="/etc/cron.d/auto_deploy_fallback"
fi

#=================================================
# REMOVE THE DATA DIRECTORY
#=================================================
ynh_script_progression --message="Removing the data directory..." --weight=2

ynh_secure_remove --file="/home/yunohost.app/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
