#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

install_type=$(ynh_app_setting_get $app install_type)
final_path=$(ynh_app_setting_get $app final_path)
ssh_host=$(ynh_app_setting_get $app ssh_host)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE DEPENDENCIES
#=================================================

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

#=================================================
# REMOVE APP MAIN DIR
#=================================================

# Remove the app directory securely
ynh_secure_remove "$final_path"

if [ "$install_type" == "main" ]
then
	#=================================================
	# REMOVE LOGROTATE CONFIGURATION
	#=================================================

	# Remove the app-specific logrotate config
	ynh_remove_logrotate
	ynh_secure_remove "/var/log/$app"
fi

#=================================================
# SPECIFIC REMOVE
#=================================================

if [ "$install_type" == "main" ]
then
	#=================================================
	# REMOVE THE CRON FILE
	#=================================================

	ynh_secure_remove "/etc/cron.d/$app"

	#=================================================
	# REMOVE THE HOST FROM THE KNOWN HOST LIST
	#=================================================

	sed -i "/$ssh_host/d" /root/.ssh/known_hosts

	#=================================================
	# REMOVE DEDICATED USER
	#=================================================

	ynh_system_user_delete $app
	ynh_secure_remove "/home/$app"

	#=================================================
	# REMOVE THE CHROOT FROM THE SSH CONFIG
	#=================================================

	sed -i "/# Automatically added by $app/d" /etc/ssh/sshd_config

	# Reload ssh service
	ynh_system_reload --service_name=ssh
else
	#=================================================
	# REMOVE THE CRON FILE
	#=================================================

	ynh_secure_remove "/etc/cron.d/auto_deploy_fallback"
fi

#=================================================
# REMOVE THE DATA DIRECTORY
#=================================================

ynh_secure_remove "/home/yunohost.app/$app"
