#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

install_type=$(ynh_app_setting_get $app install_type)
final_path=$(ynh_app_setting_get $app final_path)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE DEPENDENCIES
#=================================================

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

#=================================================
# REMOVE APP MAIN DIR
#=================================================

final_path=/opt/yunohost/$app
# Remove the app directory securely
ynh_secure_remove "$final_path"

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================

# Remove the app-specific logrotate config
ynh_remove_logrotate
ynh_secure_remove "/var/log/$app"

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE THE CRON FILE
#=================================================

# Remove a cron file
ynh_secure_remove "/etc/cron.d/$app"

#=================================================
# REMOVE THE DATA DIRECTORY
#=================================================

# Remove a cron file
ynh_secure_remove "/home/yunohost.app/$app"
