#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

app=${YNH_APP_INSTANCE_NAME:-$YNH_APP_ID}

final_path=$(ynh_app_setting_get --app=$app --key=final_path)

#=================================================
# CHECK IF ARGUMENTS ARE CORRECT
#=================================================

#=================================================
# CHECK IF AN ACTION HAS TO BE DONE
#=================================================

#=================================================
# SPECIFIC ACTION
#=================================================
# CLEAN ALL BACKUP FILES
#=================================================
ynh_script_progression --message="Cleaning all backup files" --weight=9

# Get the backup directory from the config file
backup_dir="$(grep "^main_storage_dir=" "$final_path/send_process/config.conf" | cut -d= -f2)"

while read backup_file <&3
do
	if [ -n "$backup_file" ]
	then
		ynh_print_info --message="Clean backup file $backup_file"
		ynh_secure_remove --file="$backup_dir/backup/$backup_file"
	fi
done 3<<< $(ls -1 "$backup_dir/backup" | grep ".tar.gz$")

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Execution completed" --last
