#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

app=${YNH_APP_INSTANCE_NAME:-$YNH_APP_ID}

final_path=$(ynh_app_setting_get --app=$app --key=final_path)
install_type=$(ynh_app_setting_get --app=$app --key=install_type)

#=================================================
# CHECK IF ARGUMENTS ARE CORRECT
#=================================================

#=================================================
# CHECK IF AN ACTION HAS TO BE DONE
#=================================================

if [ "$install_type" == "fallback" ]
then
    ynh_die --message="This action can be performed only on a Main server type installation of the app." --ret_code=0
fi

#=================================================
# SPECIFIC ACTION
#=================================================
# FORCE A NEW BACKUP
#=================================================
ynh_script_progression --message="Forcing a new backup..." --weight=9

ynh_exec_warn nice -n10 $final_path/send_process/send_backup.sh

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Execution completed" --last
