#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

app=${YNH_APP_INSTANCE_NAME:-$YNH_APP_ID}
final_path=$(ynh_app_setting_get $app final_path)
ssh_host=$(ynh_app_setting_get $app ssh_host)
ssh_port=$(ynh_app_setting_get $app ssh_port)
encrypt=$(ynh_app_setting_get $app encrypt)
delay_before_incident=$(ynh_app_setting_get $app delay_before_incident)
contact_mail=$(ynh_app_setting_get $app contact_mail)
auto_deploy=$(ynh_app_setting_get $app auto_deploy)

#=================================================
# SORT OUT THE CONFIG FILE TO HANDLE
#=================================================

file="$1"

if [ "$file" = "both" ]; then
	if [ "$install_type" = "main" ]; then
		config_file="$final_path/send_process/config.conf"
	else
		config_file="$final_path/deploy_process/auto_check.conf"
	fi
fi

#=================================================
# SPECIFIC ACTION
#=================================================
# RESET THE CONFIG FILE
#=================================================

# Verify the checksum and backup the file if it's different
ynh_backup_if_checksum_is_different "$config_file"

if [ "$file" = "both" ]
then
	if [ "$install_type" = "main" ]
	then
		# Get the default file and overwrite the current config
		cp "${config_file}.modele" "$config_file"

		# Recreate the default config
		ynh_replace_string "ssh_user=.*" "ssh_user=$app" "$config_file"
		ynh_replace_string "ssh_host=.*" "ssh_host=$ssh_host" "$config_file"
		ynh_replace_string "ssh_port=.*" "ssh_port=$ssh_port" "$config_file"

		data_dir="/home/yunohost.app/$app/fallback_backup"
		ynh_replace_string "main_storage_dir=.*" "main_storage_dir=$data_dir" "$config_file"
		ynh_replace_string "encrypt=.*" "encrypt=$encrypt" "$config_file"

		ssh_key="$final_path/send_process/ssh_key"
		ynh_replace_string "ssh_key=.*" "ssh_key=$ssh_key" "$config_file"

		passkey="$final_path/send_process/passkey"
		ynh_replace_string "pass_file=.*" "pass_file=$passkey" "$config_file"
	else
		# Get the default file and overwrite the current config
		cp "${config_file}.modele" "$config_file"

		# Recreate the default config
		ynh_replace_string "delay_before_incident=.*" "delay_before_incident=$delay_before_incident" "$config_file"
		ynh_replace_string "contact_mail=.*" "contact_mail=$contact_mail" "$config_file"
		ynh_replace_string "auto_deploy=.*" "auto_deploy=$auto_deploy" "$config_file"
		ynh_replace_string "__FINAL_PATH__" "$final_path" "$config_file"
	fi
fi

# Calculate and store the config file checksum into the app settings
ynh_store_file_checksum "$config_file"
