#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

app=${YNH_APP_INSTANCE_NAME:-$YNH_APP_ID}

final_path=$(ynh_app_setting_get --app=$app --key=final_path)

#=================================================
# CHECK IF ARGUMENTS ARE CORRECT
#=================================================

#=================================================
# CHECK IF AN ACTION HAS TO BE DONE
#=================================================

#=================================================
# SPECIFIC ACTION
#=================================================
# GET DNS CONFIGURATION
#=================================================
ynh_script_progression --message="Checking DNS configuration of the fallback..." --weight=1

# And the script to use to do it
auto_update_script=$(grep "^auto_update_script=" "$final_path/deploy_process/auto_check.conf" | cut -d'=' -f2)

If [ "auto_update_script" == "$final_path/DynHost/..." ]
then
    ynh_die --message="Your current configuration in \"$final_path/deploy_process/auto_check.conf\" does not specify the script to use to update your DNS. Please configure a script to use and retry."
fi

#=================================================
# FORCE A NEW BACKUP
#=================================================
ynh_script_progression --message="Updating the DNS..." --weight=9

ynh_exec_warn "$auto_update_script"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Execution completed" --last
