#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

app=${YNH_APP_INSTANCE_NAME:-$YNH_APP_ID}

final_path=$(ynh_app_setting_get --app=$app --key=final_path)
install_type=$(ynh_app_setting_get --app=$app --key=install_type)

#=================================================
# CHECK IF ARGUMENTS ARE CORRECT
#=================================================

#=================================================
# CHECK IF AN ACTION HAS TO BE DONE
#=================================================

if [ "$install_type" == "fallback" ]
then
    ynh_die --message="This action can be performed only on a Main server type installation of the app." --ret_code=0
fi

#=================================================
# SPECIFIC ACTION
#=================================================
# UPDATE THE SERVER FROM FALLBACK
#=================================================
ynh_script_progression --message="Updating the server from fallback..." --weight=9

if IS_PACKAGE_CHECK
then
    ynh_print_info --message="Do not alter the status of the fallback in Package_check."
else
    ynh_exec_warn nice -n10 $final_path/update_from_fallback_process/update_from_fallback.sh auto
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Execution completed" --last
