#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================
ynh_script_progression --message="Retrieve arguments from the manifest"

app=${YNH_APP_INSTANCE_NAME:-$YNH_APP_ID}

final_path=$(ynh_app_setting_get $app final_path)

#=================================================
# CHECK IF ARGUMENTS ARE CORRECT
#=================================================

#=================================================
# CHECK IF AN ACTION HAS TO BE DONE
#=================================================

#=================================================
# SPECIFIC ACTION
#=================================================
# UPDATE THE SERVER FROM FALLBACK
#=================================================
ynh_script_progression --message="Update the server from fallback" --weight=9

ynh_exec_warn nice -n10 $final_path/update_from_fallback_process/update_from_fallback.sh

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Execution completed" --last
