#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

app=${YNH_APP_INSTANCE_NAME:-$YNH_APP_ID}

final_path=$(ynh_app_setting_get --app=$app --key=final_path)
install_type=$(ynh_app_setting_get --app=$app --key=install_type)

#=================================================
# CHECK IF ARGUMENTS ARE CORRECT
#=================================================

#=================================================
# CHECK IF AN ACTION HAS TO BE DONE
#=================================================

if [ "$install_type" == "main" ]
then
    ynh_die --message="This action can be performed only on a Fallback server type installation of the app." --ret_code=0
fi

if [ $(grep "^auto_update_DNS=" "$final_path/deploy_process/auto_check.conf" | cut -d'=' -f2) -ne 1 ]
then
    ynh_die --message="Please set the setting auto_update_DNS to 1 into your $final_path/deploy_process/auto_check.conf in order to use this action." --ret_code=0
fi

#=================================================
# SPECIFIC ACTION
#=================================================
# GET DNS CONFIGURATION
#=================================================
ynh_script_progression --message="Checking DNS configuration of the fallback..." --weight=1

# And the script to use to do it
auto_update_script=$(grep "^auto_update_script=" "$final_path/deploy_process/auto_check.conf" | cut -d'=' -f2)

if [ "auto_update_script" == "$final_path/DynHost/..." ]
then
    ynh_die --message="Your current configuration in \"$final_path/deploy_process/auto_check.conf\" does not specify the script to use to update your DNS. Please configure a script to use and retry." --ret_code=0
fi

#=================================================
# FORCE A NEW BACKUP
#=================================================
ynh_script_progression --message="Updating the DNS..." --weight=9

ynh_exec_warn "$auto_update_script"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Execution completed" --last
